#!/bin/bash

speedtest-cli --simple > ~/blood-and-milk/.speeds 2>&1 &

gsettings set org.gnome.desktop.background picture-uri "file:///home/$USER/blood-and-milk/wall.png"

sleep 10

conky -c ~/blood-and-milk/conky_asset &
conky -c ~/blood-and-milk/conky_disk &
conky -c ~/blood-and-milk/conky_cpu_histograme.conf &

sleep 3

conky -c ~/blood-and-milk/conky_fs_disk &
conky -c ~/blood-and-milk/conky_mem_my.conf &

sleep 3

conky -c ~/blood-and-milk/conky_temperature &

sleep 3

conky -c ~/blood-and-milk/conky_gmail &
conky -c ~/blood-and-milk/conky_cpus_my &
conky -c ~/blood-and-milk/conky_notes &

sleep 3

conky -c ~/blood-and-milk/conky_connections &
conky -c ~/blood-and-milk/conky_processes &

sleep 10

conky -c ~/blood-and-milk/globus_gif &
