#!/bin/bash

speedtest-cli --simple > ~/Documents/arch_conky_blue/.speeds 2>&1 &

# gsettings set org.gnome.desktop.ba?\ckground picture-uri "file:///home/$USER/Documents/arch_conky_blue/wall.png"

# sleep 10

conky -c ~/arch_conky_blue/speedgraphs.conf &
conky -c ~/arch_conky_blue/diskgraph.conf &

# sleep 3

conky -c ~/arch_conky_blue/fsdisk.conf &
conky -c ~/arch_conky_blue/memgraph.conf &

# sleep 3

conky -c ~/arch_conky_blue/temperature_circle.conf &

# sleep 3

# conky -c ~/arch_conky_blue/conky_gmail &
conky -c ~/arch_conky_blue/cpu_circle.conf &
conky -c ~/arch_conky_blue/notes.conf &

# sleep 3

conky -c ~/arch_conky_blue/top_processes.conf &

# sleep 10
# 
# conky -c ~/arch_conky_blue/globus_gif &
